// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHBnhRh_Yi4xMNDO640IVTFkavaTMr3-A',
    appId: '1:151113953370:android:0c590591bc32754e4c6863',
    messagingSenderId: '151113953370',
    projectId: 'aishwarrya-8c144',
    databaseURL: 'https://aishwarrya-8c144-default-rtdb.firebaseio.com',
    storageBucket: 'aishwarrya-8c144.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAWzx-OLV6IP4KQW7Yd14-bQfY0odx3vU',
    appId: '1:151113953370:ios:250f1ff6b35e485c4c6863',
    messagingSenderId: '151113953370',
    projectId: 'aishwarrya-8c144',
    databaseURL: 'https://aishwarrya-8c144-default-rtdb.firebaseio.com',
    storageBucket: 'aishwarrya-8c144.firebasestorage.app',
    androidClientId: '151113953370-ac5lik9odu37no13g5hdm0l5bunilv1g.apps.googleusercontent.com',
    iosClientId: '151113953370-onhel90aaopkor9qluviu4mbdmd98blu.apps.googleusercontent.com',
    iosBundleId: 'com.pt.aishwarrya',
  );
}
